services:
  backend:
    build: .
    container_name: blog-backend
    env_file:
      - /root/blog-server.env
    ports:
      - "4000"   #internal port only
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:4000/health',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  uploads:
